---
# creation of the namespace used within the file
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
  labels:
    name: exo3

---
# autoscaling for flask deployment
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-exo3
  namespace: exo3 
spec:
  scaleTargetRef:   # which deployment want to scale
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-exo3
  minReplicas: 1     # minimum number of replicas to uses
  maxReplicas: 8     # maximum number of replicas to uses
  targetCPUUtilizationPercentage: 70  # percentage usage of the CPU over which another replicas is created

---
# Flask, we use deployment because it is easily scalable
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-exo3
  namespace: exo3 
spec: 
  replicas: 1   # single replica for a start, the autoscaling will add more as necessary
  selector:
    matchLabels:
      target: exo3
  
  template:
    metadata:
      labels:
        target: exo3
    spec: 
      containers:
      - name: container-exo3
        image: anthonyrouquier/ubuntu_flask:1.0.2   # custom image we created for flask
        # resources limitations
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "750m"
        

---
# persistent volume to link to mariadb
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mariadb-pvc
  namespace: exo3 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# mariadb, not looking to scale it so a pod is sufficient
apiVersion: v1
kind: Pod
metadata: 
  name: mariadb-pod
  namespace: exo3 
spec:
  containers:
  - name: mariadb 
    image: mariadb:10.10-rc  # one of the standard image from mariadb repository
    # resource limitations for mariadb pod
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "750m"
    env: # we need to specify a password to mariadb
    - name: MARIADB_ROOT_PASSWORD
      value: example
  volumes:  # link the previously created pvc to the pod
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: exo3-flask-svc
  namespace: exo3 

spec:
  type: NodePort  # accessible from outside network
  selector:  
    target: exo3 
  ports: 
  - port: 80
    targetPort: 80 #port ecouté par le pod ciblé  
    nodePort: 32700
    protocol: TCP
  selector:
    app: exo3

---
apiVersion: v1
kind: Service
metadata:
  name: exo3-mariadb-svc
  namespace: exo3 
  labels:
    run: exo3-mariadb
spec:
  type: ClusterIP # default option, only accessible from within the cluster
  selector:
    run: exo3-mariadb
  ports:
  - port: 6379
